[package]
name = "phant/tag"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.5.0"
SimplePath = "untakeranonplay/simplepath@0.1.1"
Trove = "sleitnick/trove@1.0.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@1.5.0"
ReplicaService = "brittonfischer/replicaservice@0.1.0"
Component = "sleitnick/component@2.4.6"
TopbarPlus = "etheroit/topbarplus@1.0.1"
RagdollSystem = "leostormer/ragdoll-system@0.3.1"